<link rel="stylesheet" href="{{ asset('assets/landing/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/landing/css/owl.carousel.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/landing/css/ticker-style.css') }}">
<link rel="stylesheet" href="{{ asset('assets/landing/css/flaticon.css') }}">
<link rel="stylesheet" href="{{ asset('assets/landing/css/slicknav.css') }}">
<link rel="stylesheet" href="{{ asset('assets/landing/css/animate.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/landing/css/magnific-popup.css') }}">
<link rel="stylesheet" href="{{ asset('assets/landing/css/fontawesome-all.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/landing/css/themify-icons.css') }}">
<link rel="stylesheet" href="{{ asset('assets/landing/css/slick.css') }}">
<link rel="stylesheet" href="{{ asset('assets/landing/css/nice-select.css') }}">
<link rel="stylesheet" href="{{ asset('assets/landing/css/style.css') }}">
<link rel="stylesheet" href="{{ asset('assets/landing/css/style.scss') }}">
